export const channels = {
  ping: 'desktop:ping',
  workspaceSelect: 'casco:workspace:select',
  workspaceCurrent: 'casco:workspace:current',
  workspaceChanged: 'casco:workspace:changed',
  workspaceFilesChanged: 'casco:workspace:files-changed',
  fsReadFile: 'casco:fs:read-file',
  fsWriteFile: 'casco:fs:write-file',
  fsCreateFile: 'casco:fs:create-file',
  fsCreateDirectory: 'casco:fs:create-directory',
  fsDeleteFile: 'casco:fs:delete-file',
  fsDeleteDirectory: 'casco:fs:delete-directory',
  fsRename: 'casco:fs:rename',
  fsReadDirectory: 'casco:fs:read-directory',
  fsSearch: 'casco:fs:search',
  terminalStart: 'casco:terminal:start-session',
  terminalExecute: 'casco:terminal:execute',
  terminalWrite: 'casco:terminal:write',
  terminalStop: 'casco:terminal:stop',
  terminalDispose: 'casco:terminal:dispose',
  terminalOutput: 'casco:terminal:output',
  terminalState: 'casco:terminal:state',
  agentStart: 'casco:agent:start',
  agentStop: 'casco:agent:stop',
  agentDecide: 'casco:agent:decide',
  agentEvent: 'casco:agent:event',
} as const
